// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: invoke.proto

package internal

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type InvokeHeader struct {
	Version              uint32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Headers              map[string][]byte `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeHeader) Reset()         { *m = InvokeHeader{} }
func (m *InvokeHeader) String() string { return proto.CompactTextString(m) }
func (*InvokeHeader) ProtoMessage()    {}
func (*InvokeHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_2156226f9a4f30f8, []int{0}
}
func (m *InvokeHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeHeader.Unmarshal(m, b)
}
func (m *InvokeHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeHeader.Marshal(b, m, deterministic)
}
func (m *InvokeHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeHeader.Merge(m, src)
}
func (m *InvokeHeader) XXX_Size() int {
	return xxx_messageInfo_InvokeHeader.Size(m)
}
func (m *InvokeHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeHeader.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeHeader proto.InternalMessageInfo

func (m *InvokeHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *InvokeHeader) GetHeaders() map[string][]byte {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*InvokeHeader)(nil), "invoke.InvokeHeader")
	proto.RegisterMapType((map[string][]byte)(nil), "invoke.InvokeHeader.HeadersEntry")
}

func init() { proto.RegisterFile("invoke.proto", fileDescriptor_2156226f9a4f30f8) }

var fileDescriptor_2156226f9a4f30f8 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcc, 0x2b, 0xcb,
	0xcf, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x16, 0x32, 0x72,
	0xf1, 0x78, 0x82, 0x99, 0x1e, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x42, 0x12, 0x5c, 0xec, 0x65, 0xa9,
	0x45, 0xc5, 0x99, 0xf9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x30, 0xae, 0x90, 0x35,
	0x17, 0x7b, 0x06, 0x58, 0x4d, 0xb1, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa2, 0x1e, 0xd4,
	0x48, 0x64, 0x03, 0xf4, 0x20, 0x54, 0xb1, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x4c, 0x87, 0x94,
	0x15, 0x17, 0x0f, 0xb2, 0x84, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0x25, 0xd8, 0x0a, 0xce, 0x20,
	0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x27, 0x08, 0xc2, 0xb1, 0x62, 0xb2, 0x60, 0x74, 0xe2, 0x8a, 0xe2, 0xc8, 0xcc, 0x2b, 0x49, 0x2d,
	0xca, 0x4b, 0xcc, 0x49, 0x62, 0x03, 0x3b, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x58,
	0x17, 0x00, 0xce, 0x00, 0x00, 0x00,
}
